#!/bin/bash
# Szybkie ustawianie wartości dla obu modeli

source ./setup
if [ "$1" == "-o" ] 
	then
	rostopic pub -1 /omnivelma/vels omnivelma/Vels -- $2 $3 $4 $5	&
fi

if [ "$1" == "-p" ] 
	then
	rostopic pub -1 /pseudovelma/vels pseudovelma/Vels -- $2 $3 $4 $5	&
fi

if [ "$1" == "-b" ] 
	then
	rostopic pub -1 /pseudovelma/vels pseudovelma/Vels -- $2 $3 $4 $5	&
	rostopic pub -1 /omnivelma/vels omnivelma/Vels -- $2 $3 $4 $5	&
fi