#!/bin/bash
# Uruchom Gazebo wraz z modelami

source setup
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:$(pwd)/src

roslaunch velmaverse velmaverse.launch &
export PIDGAZ=$!
rosrun widelnica widelnica /omnivelma/vels /pseudovelma/vels &
export PIDWID=$!
rosrun transmutator transmutator /widelnica/vels &
export PIDTRA=$!
rosrun lalkarz lalkarz -v /widelnica/vels -t /transmutator/twist &
export PIDLAL=$!

# Na ^C wyłącz wszystkie procesy
trap "kill $PIDLAL; kill $PIDTRA; kill $PIDOWID; kill $PIDGAZ;" SIGINT 

echo "Wciśnij ^C, aby wyłączyć procesy"
sleep infinity
