#!/bin/bash

#Gazebo wczytuje trzy modele, Omnivelmę, Pseudovelmę i Enkovelmę
#Widelnica dzieli Vels dla Omnivelmy i Pseudovelmy.
#Gramofon wysyła Twist do Transmutatora, który wysyła Vels do Widelnicy
#Omnivelma wysyła Enkodery do Dziadziusia, który wysyła je do Enkovelmy

if [ $# -ne 1 ]
then
	echo $0: PLIK_GRAMOFON > /dev/stderr
	exit $EXITERR
fi

GRAMOFON_FILE=$1
if [ ! -f $GRAMOFON_FILE ]
then
	echo $0: Plik $GRAMOFON_FILE nie istnieje > /dev/stderr
	exit $EXITERR
fi

commands=(
"rosbag record -O $ROSBAG_FILE /omnivelma/pose /pseudovelma/pose /enkovelma/pose /omnicznica/relative /enkocznica/relative" 
"roslaunch velmaverse triplevelma.launch"
"rosrun widelnica widelnica /omnivelma/vels /pseudovelma/vels"
"rosrun transmutator transmutator /widelnica/vels"
"rosrun dziadzio dziadzio /omnivelma/encoders /enkovelma/vels"
"rosrun gramofon gramofon 0.02 $GRAMOFON_FILE /transmutator/twist"
"rqt_multiplot --multiplot-config $RQT_MULTIPLOT_DIR/triple.xml --multiplot-run-all"
)


