#!/bin/bash

#Gazebo wczytuje dwa modele, Omnivelmę i Pseudovelmę
#Widelnica dzieli Vels dla Omnivelmy i Pseudovelmy.
#Gramofon wysyła Twist do Transmutatora, który wysyła Vels do Widelnicy

if [ $# -ne 1 ]
then
	echo $0: PLIK_GRAMOFON > /dev/stderr
	exit $EXITERR
fi

GRAMOFON_FILE=$1
if [ ! -f $GRAMOFON_FILE ]
then
	echo $0: Plik $GRAMOFON_FILE nie istnieje > /dev/stderr
	exit $EXITERR
fi

commands=(
"rosbag record -O /tmp/bag_gramofon_pose /omnivelma/pose /pseudovelma/pose"
"roslaunch velmaverse velmaverse.launch"
"rosrun widelnica widelnica /omnivelma/vels /pseudovelma/vels"
"rosrun transmutator transmutator /widelnica/vels"
"rosrun gramofon gramofon 0.1 $GRAMOFON_FILE /transmutator/twist"
"rqt_multiplot --multiplot-config $RQT_MULTIPLOT_DIR/gazebo.xml --multiplot-run-all"
)

