#!/bin/bash

#Gazebo wczytuje dwa modele, Omnivelmę i Pseudovelmę
#Widelnica dzieli Vels dla Omnivelmy i Pseudovelmy.
#Gramofon wysyła Twist do Transmutatora, który wysyła Vels do Widelnicy

commands=(
"rosbag record -O $ROSBAG_FILE /omnivelma/pose /wewucho/imu"
"roslaunch velmaverse velmaverse.launch"
"rosrun widelnica widelnica /omnivelma/vels /pseudovelma/vels"
"rosrun transmutator transmutator /widelnica/vels"
"rosrun lalkarz lalkarz -v /widelnica/vels -t /transmutator/twist"
"rqt_multiplot --multiplot-config $RQT_MULTIPLOT_DIR/wewucho.xml --multiplot-run-all"
)

