#!/bin/bash

#Uruchom Gazebo
#Gazebo wczytuje dwa modele, Omnivelmę i Pseudovelmę(która się nie rusza)
#Pantofelek wczytuje skanery i wysyła Twist do Transmutatora
#Transmutator wysyła do Omnivelmy

source setup
#Ustaw ścieżkę modeli dla Gazebo
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:$(pwd)/src
roslaunch velmaverse solovelma.launch &
PIDGAZ=$!
rosrun transmutator transmutator /omnivelma/vels &
PIDTRA=$!
rosrun pantofelek pantofelek /transmutator/twist /monokl_l/scan /monokl_r/scan &
PIDPAN=$!
trap "kill $PIDPAN; kill $PIDTRA kill $PIDGAZ;" SIGINT 

echo "Wciśnij ^C, aby wyłączyć procesy"
sleep infinity
