#!/bin/bash

#Gazebo wczytuje Omnivelmę
#Gramofon wysyła Twist do Transmutatora, który wysyła Vels do Omnivelmy

if [ $# -ne 1 ]
then
	echo $0: PLIK_GRAMOFON > /dev/stderr
	exit $EXITERR
fi

GRAMOFON_FILE=$1
if [ ! -f $GRAMOFON_FILE ]
then
	echo $0: Plik $GRAMOFON_FILE nie istnieje > /dev/stderr
	exit $EXITERR
fi

commands=(
"rosbag record -O $ROSBAG_FILE /wewucho/imu /odszumiacz/imu /omnivelma/twist"
"rosrun odszumiacz odszumiacz /wewucho/imu /odszumiacz/imu 10"
"roslaunch velmaverse solovelma.launch"
"rosrun transmutator transmutator /omnivelma/vels"
"rosrun gramofon gramofon 0.1 $GRAMOFON_FILE /transmutator/twist"
"rqt_multiplot --multiplot-config $RQT_MULTIPLOT_DIR/wewucho.xml --multiplot-run-all"
)

